baseURL = 'https://andrelohde.com/'
locale = 'en-us'
title = 'André Lohde | PhD researcher in quantum metrology'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# menu
# [[menus.main]]
# # Blog posts
#     name = "Posts"
#     url = "/posts/"
#     weight = 10

# # About my research
# [[menus.main]]
#     name = "Publications"
#     url = "/publications/"
#     weight = 20

# # My CV
# [[menus.main]]
#     name = "About me"
#     url = "/about/"
#     weight = 30

[params]
    defaultTheme = "light"
    #disableThemeToggle = true
    home = "/about/"
    showFullContents = false

[markup.goldmark.renderer]
    unsafe = true # allow raw html